# 텐서플로의 주요 특징

텐서: 테이터를 담고 있는 다차원 배열에 대한 일반화된 수학적 용어.
텐서 차원을 일반적으로 랭크 라고 부른다.

랭크 - 차원

### 텐서의 랭크와 크기를 확인하는 방법

tf.rank 함수를 사용하여 텐서 랭크를 확인할 수 있다. 예를 들어 X가 텐서라면 X.get_shape()을 사용하여 크기를 구합니다. 이 메서드는 TensorShape이라는 특별한 클래스의 객체를 반환환다. tf.rank 함수와 텐서의 get_shape 메서드를 사용하여 텐서 객체의 랭크와 크기를 추출


In [1]:
import tensorflow as tf
import numpy as np

t1 = tf.constant(np.pi)
t2 = tf.constant([1, 2, 3, 4])
t3 = tf.constant([[1, 2], [3, 4]])

## 랭크를 구한다.
r1 = tf.rank(t1)
r2 = tf.rank(t2)
r3 = tf.rank(t3)

## 크기를 구한다.
s1 = t1.get_shape()
s2 = t2.get_shape()
s3 = t3.get_shape()

In [2]:
print('크기', s1, s2, s3)
print('랭크', r1.numpy(), r2.numpy(), r3.numpy())

크기 () (4,) (2, 2)
랭크 0 1 2


### 텐서를 다차원 배열로 변환

일부 연산들은 넘파이 배열 연산과 매우 비슷하게 작동.
랭크 2 이상인 텐서를 다룰 때 전치 같은 변환은 주의를 기울여야 한다.
넘파이는 shape 속성으로 배열 크기를 얻는다.
TF 는 tf.get_shape 함수를 사용한다.
또는 텐서의 shape 속성을 사용한다.


In [3]:
arr = np.array([[1., 2., 3., 3.5],
              [4., 5., 6., 6.5],
              [7., 8., 9., 9.5]])

T1 = tf.constant(arr)
print(T1)

tf.Tensor(
[[1.  2.  3.  3.5]
 [4.  5.  6.  6.5]
 [7.  8.  9.  9.5]], shape=(3, 4), dtype=float64)


In [4]:
s = T1.get_shape()

In [5]:
print('T1의 크기', s)
print('T1의 크기', T1.shape)

T1의 크기 (3, 4)
T1의 크기 (3, 4)


In [6]:
T2 = tf.Variable(np.random.normal(size = s))

In [7]:
print(T2)

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float64, numpy=
array([[ 0.14776593,  0.17795802, -2.04774627, -1.06025732],
       [ 2.64173889,  0.0084694 ,  0.03339911, -0.16470154],
       [-2.31474699,  0.21494321,  0.70216527,  0.77758085]])>


In [8]:
T3 = tf.Variable(np.random.normal(size = s[0 ]))
print(T3)

<tf.Variable 'Variable:0' shape=(3,) dtype=float64, numpy=array([0.51213483, 0.11894048, 0.38058718])>


In [9]:
T4 = tf.reshape(T1, shape=[1,1,-1])
print(T4)

tf.Tensor([[[1.  2.  3.  3.5 4.  5.  6.  6.5 7.  8.  9.  9.5]]], shape=(1, 1, 12), dtype=float64)


In [10]:
T5 = tf.reshape(T1, shape =[1, 3, -1])
print(T5)

tf.Tensor(
[[[1.  2.  3.  3.5]
  [4.  5.  6.  6.5]
  [7.  8.  9.  9.5]]], shape=(1, 3, 4), dtype=float64)


In [11]:
T6 = tf.transpose(T5, perm=[2, 1, 0])
print(T6)

tf.Tensor(
[[[1. ]
  [4. ]
  [7. ]]

 [[2. ]
  [5. ]
  [8. ]]

 [[3. ]
  [6. ]
  [9. ]]

 [[3.5]
  [6.5]
  [9.5]]], shape=(4, 3, 1), dtype=float64)


In [12]:
T7 = tf.transpose(T5, perm = [0, 2, 1])
print(T7)

tf.Tensor(
[[[1.  4.  7. ]
  [2.  5.  8. ]
  [3.  6.  9. ]
  [3.5 6.5 9.5]]], shape=(1, 4, 3), dtype=float64)


In [13]:
t5_split = tf.split(T5, num_or_size_splits = 2, axis = 2)
print(t5_split) ## 출력은 텐서의 리스트

[<tf.Tensor: id=36, shape=(1, 3, 2), dtype=float64, numpy=
array([[[1., 2.],
        [4., 5.],
        [7., 8.]]])>, <tf.Tensor: id=37, shape=(1, 3, 2), dtype=float64, numpy=
array([[[3. , 3.5],
        [6. , 6.5],
        [9. , 9.5]]])>]


In [14]:
t1 = tf.ones(shape=(5, 1), dtype=tf.float32)
t2 = tf.zeros(shape=(5, 1), dtype = tf.float32)
print(t1, t2)

tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]], shape=(5, 1), dtype=float32) tf.Tensor(
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(5, 1), dtype=float32)


In [15]:
t3 = tf.concat([t1, t2], axis = 0)
t4 = tf.concat([t1, t2], axis = 1)
print(t3,t4)

tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]], shape=(10, 1), dtype=float32) tf.Tensor(
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]], shape=(5, 2), dtype=float32)


### tensorflow 계산 그래프 이해 1. x버전

1. 비어있는 새로운 계산 그래프르를 만든다.
2. 계산 그래프에 노드를 추가한다.
3. 그래프를 실행한다.
   <br> a.  새로운 세션을 시작한다.<br>
   <br> b. 그래프에 있는 변수를 초기화한다. <br>
   <br> c. 이 세션에서 계산 그래프를 실행한다.<br>

## tensorflow 계산 그래프 2.x 버전

텐서플로 2 버전에서는 tf.function 데코레이터를 사용하여 일반 파이썬 함수를 호출 가능한 그래프 객체로 만든다.
마치 tf.Graph와 tf.Session 을 합쳐 놓은 것처럼 생각할 수 있다. 앞 코드를 tf.function 데코레이털르 사용하여 작성한다.

In [16]:
@tf.function
def simple_func():
    a = tf.constant(1)
    b = tf.constant(2)
    c = tf.constant(3)
    
    z = 2*(a - b) + c
    return z

print(simple_func().numpy())

1


In [17]:
print(simple_func.__class__)

<class 'tensorflow.python.eager.def_function.Function'>


In [18]:
## 같은 표현
def simple_func():
    a = tf.constant(1)
    b = tf.constant(2)
    c = tf.constant(3)
    
    z = 2*(a - b) + c
    return z

simple_func = tf.function(simple_func)

tf.function으로 감싼 함수 안의 연산은 자동으로 텐서플로 그래프에 포함되어 실행된다. 이를 AutoGraph 기능이라고 한다.

In [19]:
con_func = simple_func.get_concrete_function()
con_func.graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'sub' type=Sub>,
 <tf.Operation 'mul/x' type=Const>,
 <tf.Operation 'mul' type=Mul>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'Identity' type=Identity>]

In [20]:
con_func.graph.as_graph_def()

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 1
      }
    }
  }
}
node {
  name: "Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Const_2"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "sub"
  op: "Sub"
  input: "Const"
  input: "Const_1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "mul/x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32

## 텐서플로우의 변수

텐서 플로에서 변수는 특별한 종류의 텐서 객체이다. 훈련 과정 동안 모델 파라미터를 저장하고 업데이트할 수 있습니다. 예를 들어 신경망의 입력층, 은닉층, 출력층에 있는 가중치입니다. 변수를 정의할 때 초기 텐서 값을 지정해야 한다.

텐서플로 변수를 정의하는 방법은 다음과 같다.
tf.Variable(<initial-value>, name=<optional-name>)
    
tf.Variable 에는 shape이나 dtype을 설정할 수 없다. 크기와 타입은 초기값과 동일하게 설정됩니다.

In [21]:
w2 = tf.Variable(np.array([[1,2,3,4], [5,6,7,8]]), name = 'w2')
print(w2)


<tf.Variable 'w2:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>


In [22]:
print(w2 + 1)

tf.Tensor(
[[2 3 4 5]
 [6 7 8 9]], shape=(2, 4), dtype=int32)


### tf.keras API 자세히 배우기

## Sequential 모델

sequential 모델은 층을 순서대로 쌓은 모델을 만든다. 

In [23]:
import matplotlib.pyplot as plt

np.random.seed(0)

def make_random_data():
    x = np.random.uniform(low = -2, high = 2, size = 200)
    y = []
    for t in x:
        r = np.random.normal(loc = 0.0, scale =(0.5 + t *t/ 3),
                            size = None)
        y.append(r)
    return x, 1.726 * x - 0.84 + np.array(y)

x, y = make_random_data()
plt.plot(x, y, 'o')
plt.show()

<Figure size 640x480 with 1 Axes>

In [24]:
x_train, y_train = x[:150], y[:150]
x_test, y_test = x[150:], y[150:]

In [25]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=1, input_dim = 1))

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [28]:
model.compile(optimizer='sgd', loss ='mse')
history = model.fit(x_train, y_train, epochs = 100, validation_split=0.3)

Train on 105 samples, validate on 45 samples
Epoch 1/100
105/105 [==============================] - 0s 1ms/sample - loss: 0.7567 - val_loss: 0.9010
Epoch 2/100
105/105 [==============================] - 0s 114us/sample - loss: 0.7573 - val_loss: 0.8997
Epoch 3/100
105/105 [==============================] - 0s 114us/sample - loss: 0.7561 - val_loss: 0.8982
Epoch 4/100
105/105 [==============================] - 0s 123us/sample - loss: 0.7570 - val_loss: 0.8987
Epoch 5/100
105/105 [==============================] - 0s 123us/sample - loss: 0.7559 - val_loss: 0.8986
Epoch 6/100
105/105 [==============================] - 0s 114us/sample - loss: 0.7562 - val_loss: 0.8991
Epoch 7/100
105/105 [==============================] - 0s 114us/sample - loss: 0.7569 - val_loss: 0.9033
Epoch 8/100
105/105 [==============================] - 0s 123us/sample - loss: 0.7575 - val_loss: 0.9017
Epoch 9/100
105/105 [==============================] - 0s 114us/sample - loss: 0.7568 - val_loss: 0.9041
Epoch 10/100

Epoch 78/100
105/105 [==============================] - 0s 114us/sample - loss: 0.7559 - val_loss: 0.9039
Epoch 79/100
105/105 [==============================] - 0s 114us/sample - loss: 0.7561 - val_loss: 0.9023
Epoch 80/100
105/105 [==============================] - 0s 123us/sample - loss: 0.7579 - val_loss: 0.9036
Epoch 81/100
105/105 [==============================] - 0s 123us/sample - loss: 0.7564 - val_loss: 0.9012
Epoch 82/100
105/105 [==============================] - 0s 114us/sample - loss: 0.7567 - val_loss: 0.9033
Epoch 83/100
105/105 [==============================] - 0s 114us/sample - loss: 0.7574 - val_loss: 0.9014
Epoch 84/100
105/105 [==============================] - 0s 123us/sample - loss: 0.7560 - val_loss: 0.8994
Epoch 85/100
105/105 [==============================] - 0s 123us/sample - loss: 0.7564 - val_loss: 0.9030
Epoch 86/100
105/105 [==============================] - 0s 114us/sample - loss: 0.7565 - val_loss: 0.9035
Epoch 87/100
105/105 [========================

### 함수형 API

sequential 모델은 층을 순서대로 쌓은 네트워크를 만든다. 이따금 보다 더 복잡한 모델을 만들어야 할 때가 있다. tf.keras의 함수형 APT는 다양한 토폴로지의 네트워크를 만들 수 있습니다. 함수형 api에서는 입력과 출력 사이에 원하는 층을 자유롭게 조합할 수 있습니다.

In [34]:
from tensorflow.keras import Model , Input
input = tf.keras.Input(shape=(1,))
output = tf.keras.layers.Dense(1)(input)

먼저 튜플로 입력 크기를 지정하여 Input 클래스의 객체를 만듭니다. 그 다음 앞서 보았던 Dense 클래스를 마치 함수처럼 호출하고 있습니다. 클래스 객체를 함수처럼 호출할 수 있는 파이썬의 특수한  __call__() 메서드를 이용한 것이다. 마지막 코드는 다음과 같이 쓴다.


In [37]:
dense = tf.keras.layers.Dense(1)
output = dense(input)

# 또는

dense = tf.keras.layers.Dense(1)
output = dense.__call__(input)

In [39]:
model = tf.keras.Model(input, output)
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 1)]               0         
_________________________________________________________________
dense_7 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [41]:
model.compile(optimizer='sgd', loss='mse')
history = model.fit(x_train, y_train, epochs = 500, validation_split = 0.3)

Train on 105 samples, validate on 45 samples
Epoch 1/500
105/105 [==============================] - 0s 2ms/sample - loss: 4.3373 - val_loss: 2.7028
Epoch 2/500
105/105 [==============================] - 0s 123us/sample - loss: 3.7338 - val_loss: 2.3851
Epoch 3/500
105/105 [==============================] - 0s 133us/sample - loss: 3.2105 - val_loss: 2.1108
Epoch 4/500
105/105 [==============================] - 0s 123us/sample - loss: 2.7629 - val_loss: 1.8896
Epoch 5/500
105/105 [==============================] - 0s 114us/sample - loss: 2.3969 - val_loss: 1.6812
Epoch 6/500
105/105 [==============================] - 0s 123us/sample - loss: 2.0617 - val_loss: 1.5483
Epoch 7/500
105/105 [==============================] - 0s 123us/sample - loss: 1.8256 - val_loss: 1.4333
Epoch 8/500
105/105 [==============================] - 0s 123us/sample - loss: 1.6303 - val_loss: 1.3356
Epoch 9/500
105/105 [==============================] - 0s 123us/sample - loss: 1.4646 - val_loss: 1.2334
Epoch 10/500

Epoch 78/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7562 - val_loss: 0.8976
Epoch 79/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7565 - val_loss: 0.8988
Epoch 80/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7581 - val_loss: 0.8998
Epoch 81/500
105/105 [==============================] - 0s 133us/sample - loss: 0.7562 - val_loss: 0.8982
Epoch 82/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7563 - val_loss: 0.8964
Epoch 83/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7569 - val_loss: 0.8928
Epoch 84/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7570 - val_loss: 0.8975
Epoch 85/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7576 - val_loss: 0.8958
Epoch 86/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7578 - val_loss: 0.8953
Epoch 87/500
105/105 [========================

Epoch 155/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7564 - val_loss: 0.9039
Epoch 156/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7559 - val_loss: 0.9021
Epoch 157/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7560 - val_loss: 0.9044
Epoch 158/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7567 - val_loss: 0.9032
Epoch 159/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7563 - val_loss: 0.9044
Epoch 160/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7576 - val_loss: 0.9011
Epoch 161/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7562 - val_loss: 0.8958
Epoch 162/500
105/105 [==============================] - 0s 104us/sample - loss: 0.7568 - val_loss: 0.8987
Epoch 163/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7563 - val_loss: 0.9027
Epoch 164/500
105/105 [==============

105/105 [==============================] - 0s 123us/sample - loss: 0.7572 - val_loss: 0.9080
Epoch 232/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7575 - val_loss: 0.9049
Epoch 233/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7566 - val_loss: 0.9097
Epoch 234/500
105/105 [==============================] - 0s 104us/sample - loss: 0.7568 - val_loss: 0.9058
Epoch 235/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7567 - val_loss: 0.9110
Epoch 236/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7571 - val_loss: 0.9104
Epoch 237/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7566 - val_loss: 0.9084
Epoch 238/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7562 - val_loss: 0.9074
Epoch 239/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7557 - val_loss: 0.9075
Epoch 240/500
105/105 [============================

105/105 [==============================] - 0s 114us/sample - loss: 0.7563 - val_loss: 0.9031
Epoch 308/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7568 - val_loss: 0.9008
Epoch 309/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7563 - val_loss: 0.9056
Epoch 310/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7555 - val_loss: 0.9060
Epoch 311/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7558 - val_loss: 0.9071
Epoch 312/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7566 - val_loss: 0.9067
Epoch 313/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7569 - val_loss: 0.9089
Epoch 314/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7562 - val_loss: 0.9131
Epoch 315/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7563 - val_loss: 0.9097
Epoch 316/500
105/105 [============================

105/105 [==============================] - 0s 114us/sample - loss: 0.7575 - val_loss: 0.8978
Epoch 384/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7561 - val_loss: 0.8979
Epoch 385/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7562 - val_loss: 0.8983
Epoch 386/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7565 - val_loss: 0.9011
Epoch 387/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7563 - val_loss: 0.9008
Epoch 388/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7581 - val_loss: 0.8975
Epoch 389/500
105/105 [==============================] - 0s 104us/sample - loss: 0.7562 - val_loss: 0.8980
Epoch 390/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7569 - val_loss: 0.8961
Epoch 391/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7577 - val_loss: 0.8996
Epoch 392/500
105/105 [============================

105/105 [==============================] - 0s 114us/sample - loss: 0.7595 - val_loss: 0.9249
Epoch 460/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7594 - val_loss: 0.9222
Epoch 461/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7575 - val_loss: 0.9215
Epoch 462/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7577 - val_loss: 0.9249
Epoch 463/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7575 - val_loss: 0.9186
Epoch 464/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7572 - val_loss: 0.9173
Epoch 465/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7569 - val_loss: 0.9158
Epoch 466/500
105/105 [==============================] - 0s 123us/sample - loss: 0.7565 - val_loss: 0.9201
Epoch 467/500
105/105 [==============================] - 0s 114us/sample - loss: 0.7573 - val_loss: 0.9226
Epoch 468/500
105/105 [============================